### ISSUE TITLE
Ajouter la  méthode de partitionnement avec divergence de Bregman

### ISSUE THREAD

**Issue by clairebrecheteau** [pnavaro/GeometricClusterAnalysis.jl#4]
Se référer au tuto : 
Fichier Rmd : https://plmlab.math.cnrs.fr/brecheteau/trimmed-bregman-clustering/
Fichier html : https://brecheteau.pages.math.cnrs.fr/trimmed-bregman-clustering/

**Comment by pnavaro** [comment]
J'ai amélioré l'example obama, j'ai bidouillé avec la PCA et la LDA, j'ai fait des trucs de cuisine par déduction, désolé Claire ;-P  Faudra que tu m'expliques.
Il y a  peu près tout mais faudrait qu'on revoir le tout ensemble.

**Comment by pnavaro** [comment]
https://pnavaro.github.io/GeometricClusterAnalysis.jl/dev/obama/

**Comment by clairebrecheteau** [comment]
D'accord Pierre, merci... 
Tu reviens quand à Rennes ? Tu veux passer un jour à Rennes 2 avant le 26 août ?

**Comment by pnavaro** [comment]
C'est drôle de recevoir ce message seulement maintenant :-)
