### ISSUE TITLE
2 méthodes d'affichage des unions ellipses avec hclust

### ISSUE THREAD

**Issue by clairebrecheteau** [pnavaro/GeometricClusterAnalysis.jl#9]
Créer deux fonctions différentes d'affichage des points : 
- Une qui fait ce qui est fait actuellement qui affiche juste les changements d'étapes
- Une indexée par le temps qui fait grossir les ellipses petit à petit et d'arrête quand on atteint le nombre de points trimmés (?)

**Comment by pnavaro** [comment]
Je pense qu'on a à peu près tout, il faut travailler sur l'interface. Je propose de mettre cette demande avec l'issue #10 

Duplicate of #10
